# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  DOCKER_REGISTRY: public.ecr.aws/fscasual/gogogadget      
jobs:
  build:
    name: build and publish Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5
      - name: Get version
        id: versions
        run: |
          version=$(<VERSION)
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "snapshot-version=${version}-$(git log --format=%h -1)" >> $GITHUB_OUTPUT

      - name: Check if Tag Exists
        id: check_tag
        run: |
          git ls-remote --exit-code --tags origin '${{ steps.versions.outputs.version }}' && found=true
          if [[ "${found}" == "true" ]]; then
            echo "::error::The ${{ steps.versions.outputs.version }} tag already exists. Please update the version and changelog."
            exit 1
          fi
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::070936606018:role/gha_ecr_role
      - name: Log in to AWS ACR Public
        uses: aws-actions/amazon-ecr-login@v2    
        with:
          registry-type: public
      
      - name: set up goreleaser args
        id: goreleaser-args
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            git tag ${{ steps.versions.outputs.snapshot-version }}
            echo "args=--snapshot" >> $GITHUB_OUTPUT
          else
            echo "args= " >> $GITHUB_OUTPUT
          fi
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: v2
          args: release --clean ${{ steps.goreleaser-args.outputs.args }}

      - name: push Docker image
        run: |
            docker push ${{ env.DOCKER_REGISTRY }}:${{ steps.versions.outputs.version }}-amd64
            docker push ${{ env.DOCKER_REGISTRY }}:${{ steps.versions.outputs.version }}-arm64
      
      # - name: Generate artifact attestation
      #   uses: actions/attest-build-provenance@v3
      #   with:
      #     subject-name: index.docker.io/my-docker-hub-namespace/my-docker-hub-repository
      #     subject-digest: ${{ steps.push.outputs.digest }}
      #     push-to-registry: true
